### ISSUE TITLE
Home Assistant and IPv6

### ISSUE THREAD

**Issue by DidierLmn** [home-assistant/hassos#127]
Hass.io Supervisor 115
HassOS 1.7
Home-Assistant 0.74
Raspberry Pi 2 B

Home Assistant does not get an IPv6 address on my router, while other devices do get an IPv6 address. 
Is IPv6 supported in HassOS?
If so, what configs/logs/... can I check to find the problem or enable IPv6 support?

**Comment by pvizeli** [comment]
https://www.google.com/search?q=linux+networkmanager+ipv6&oq=linux+networkmanager+ipv6&aqs=chrome..69i57j0.5166j0j7&sourceid=chrome&ie=UTF-8

**Comment by tjorim** [comment]
Weird, my setup does get an IPv6.
Are you using any custom NetworkManager connection files?
The default profile should get an IPv6 address.

**Comment by bayi** [comment]
The default profile has ipv6 in it ( look at: https://github.com/home-assistant/hassos/blob/dev/buildroot-external/rootfs-overlay/usr/share/system-connections/default ),

even adding an explicit config doesnt help here, Hassos isnt receiving an ipv6 address and ipv6 network is broken ( i see a log entries about not able to reach some of my zeroconf services because of that ).

I just restored my old Hassio installation with resin and it worked there, while Hassos isnt receiving an address.

@tjorim can u please confirm that your device has a working ipv6 ?

**Comment by bayi** [comment]
@pvizeli is this enough information to reopen this issue ? 
I just reinstalled HassOS newest and it isnt receiving any ipv6 address no matter what i do.

What can i do to help you out with more information ?

**Comment by widder** [comment]
What method are you using to get the IPv6 address? I tried it today and it's working fine with SLAAC
