### ISSUE TITLE
[wishlist] Generic PC board

### ISSUE THREAD

**Issue by chrysn** [home-assistant/hassos#197]
For use with generic PCs (used to call them "IBM compatible"), I think that it would enhance user experience if there were an image that could be written to their hard disk just as one loads the raspi image onto an SD card. (More on rationale and use case [is described on the community forum](https://community.home-assistant.io/t/hass-io-on-generic-pc-hardware/68110/17)).

I tested the OVA image, as it should already be suited for that task, and found that it did boot up, start various docker processes, and resized the disk partitions to fit the actual disk.

Where it failed was configuring the network; the host's ethernet interface (a Intel Gigabit I221, the only network interface available) never sent out a single package. As the USB keyboard was unavailable after leaving the bootloader (pressing m and selecting a boot image, and using that shell worked), I could not drill down further on what exactly failed.

When tested with a Debian netinstaller, the ethernet interface is detected automatically and brought up without requiring any nonfree firmware; it could, however, be that free firmware was uploaded into the network adapter in the course of configuring the network interface.

Would you generally consider a generic PC image for inclusion in the build process? If so, do you have pointers to how to adapt the OVA build process to obtain an image that works on any amd64 system?

**Comment by jtru** [comment]
I only started to look at the OVA image yesterday in the evening, but from what I've seen, your problem could very probably be solved by including the proper NIC drivers for your card - the current config supports `virtio` devices primarily, and you can't have that in a physical machine.

Since there's a _lot_ of NIC drivers kicking around in Linux, the question a generic build config would have to answer is which ones to build/support, since they will end up bloating the image, which might be a concern to some.

You can always put a hypervisor in between your host and hassos though, which would solve that particular driver support problem en passant, while "wasting" a tiny bit of extra resources on the host. Qemu works with some trickery involved, but the situation is only going to improve on that front :)
