### ISSUE TITLE
Hassos NTP feature

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/hassos#270]
i see in hassos 1.13 a new NTP feature? what is this about?
i have an issue, when i reboot Hassos1.13 ,  (vmdk) that the timezone is 1 hour behind, because my timezone is ETA +1 
so all my sensors are not working in the first hour, or i just need to restart the HASS.io (restart config) just after the first  reboot of hassos , then its also solved... then my sensors are correct :)

so how does this NTP feature work?

thnx

**Comment by ascillato** [comment]
@pvizeli 

Hi,

Can NTP be used to sync time for other devices in the network using http://hassio.local:123 ?

**Comment by pvizeli** [comment]
@ascillato that need to be an add-on. You can create an add-on for time sync server and make a PR on core repository 👍

**Comment by tinysnake** [comment]
I have a problem to proper install hass.io because of the time is way off so that unable to pull repositories from docker. I think the ntp server is inaccessible from China.
for more information please [read this forum post](https://community.home-assistant.io/t/connection-refused-frontend-doesnt-load-fresh-install/72675)

I'm pretty much a noob to docker and linux stuff, so I think could you add a feature to set the ntp server from file, like the "config/network/my-network" file, thanks!
