### ISSUE TITLE
how to install additional apps?

### ISSUE THREAD

**Issue by lpt2007** [home-assistant/hassos#342]
how can I install additional apps? Like (mc)mindnight commander?

**Comment by pvizeli** [comment]
That is a hypervisor for docker. So everything needs run inside a container.

**Comment by lpt2007** [comment]
how can I do that?

**Comment by Apipa169** [comment]
The easiest way to do that is install Portainer via the Hass.io community add-ons and get yourself familiar with Docker. ([https://training.play-with-docker.com/ops-stage1/](https://training.play-with-docker.com/ops-stage1/))

Maybe there is already a Docker image for your app, otherwise you can create your own.
